Get themes from external repo and build tokens locally
compassion-gds/compassion-gds pull request #131
Opened 2022-12-01 15:18 UTC by KerimRahman

Open for discussion.

2022-12-05 12:05 UTC, kidroca approved these changes
Looks good overall 

One thing that seems to remain is to fetch the tokens from Figma repo at the build step 
Right now they have to be manually copied to the project right?

Can we continue with a PR for the functionality that fetches the tokens from Figma repo

2022-12-05 12:05 UTC, kidroca commented on package.json
> +    "transform-dark": "npx token-transformer themes tokens/_cds-dark/tokens.json core/cds-core,cds-dark/theme-cds-dark,components/accordion,components/alert,components/background,components/badge,com
Why do we have to list all these items here

```
core/cds-core,cds-light/theme-cds-light,components/accordion,components/alert,components/background...
```

Can they come from config? Or at least something like `components/*` ?

2022-12-05 13:17 UTC, KerimRahman commented on package.json
> +    "transform-dark": "npx token-transformer themes tokens/_cds-dark/tokens.json core/cds-core,cds-dark/theme-cds-dark,components/accordion,components/alert,components/background,components/badge,com
I don't think the transformer supports `components/*`. At least, I haven't found that in the docs. Also, that's how it's done in the `cds-token` repo though.

2022-12-05 16:54 UTC, kidroca requested changes
Took another look at the changes and noticed they are added on the root `package.json` and produce results at the root of the monorepo 

This should instead be moved to a separate project in `packages` 

Added a few more notes 

Can you update the PR description with what is expected to happen
I've tried the build command everything runs successfully but I see this at the end:

```
Processing: [_cds-light]

scss
No properties for _cds-light.css. File not created.
...
```
_(same for \_cds-dark)_

It seems no css (variables?) is being output, and the tokens are empty 
`tokens/_cds-light/tokens.json` has this content `{}`

2022-12-05 16:54 UTC, kidroca commented on build.js
> +const { kebabCase, isPx, transformShadow } = require('./utils');
There are unused items here

2022-12-05 16:54 UTC, kidroca commented on package.json
> +    "transform-dark": "npx token-transformer themes tokens/_cds-dark/tokens.json core/cds-core,cds-dark/theme-cds-dark,components/accordion,components/alert,components/background,components/badge,com
I've checked out `token-transformer` and the example there just uses `components` and not listing every component folder, can we try that?

2022-12-05 16:54 UTC, kidroca commented on package.json
> +    "transform-light": "npx token-transformer themes tokens/_cds-light/tokens.json core/cds-core,cds-light/theme-cds-light,components/accordion,components/alert,components/background,components/badge
Can we move these to a separate shell script so it's easy to document everything in the script - why we do stuff, what are the parameters etc...

We should also delete anything unused in the end, or at least add it to gitignore

2022-12-09 14:19 UTC, kidroca requested changes
Looks good 

Can you put the `themes` folder to `.gitignore` 
Similar to how the `dist` folder in other packages is ignored 

The end goal for this package would be to have a `dist` folder with a few css files (e.g. variables-light/dark.css and a bunch of theme-{name}.css)

For the current PR it would be enough to just ignore the `themes` folder and update package names

2022-12-09 14:19 UTC, kidroca commented on package.json
> +    "packages/cds-css"
The workspace should be just `packages/css` or `packages/css-core`

2022-12-09 14:19 UTC, kidroca commented on packages/cds-css/package.json
> +  "name": "@compassion-gds/cds-css",
The name `@compassion-gds/cds-css` is a bit of tautology - CDS is compassion-gds (Compassion Design System) it should be `@compassion-gds/css` or `@compassion-gds/css-core`

2022-12-09 15:18 UTC, kidroca approved these changes
LGTM

2022-12-09 15:18 UTC, merged