React | Table component/stories
compassion-gds/compassion-gds pull request #155
Opened 2023-03-07 12:06 UTC by KerimRahman

2023-03-08 14:41 UTC, kidroca requested changes

2023-03-08 14:41 UTC, kidroca commented on packages/react/src/components/Table/Table.tsx
> +    <div className="table-container" style={containerStyle}>
What's the purpose of the container, can the table render without (is it needed 100% of the time?)

It would be easier to manage classes and styles if the container was a separate component, to allow usages like

#### without container
```js
<Table style={{...}} className="custom-table" {...} />
```

#### with container
```jsx
<TableContainer style={{...}} className="custom-table-container">
  <Table style={{...}} className="custom-table" {...} />
</TableContainer>
```

---

In any case, it should be possible to pass a class name at least for the container

2023-03-08 15:02 UTC, KerimRahman commented on packages/react/src/components/Table/Table.tsx
> +    <div className="table-container" style={containerStyle}>
The container is needed, because of the `overflow-x: auto;`, so when there isn't enough space, it just gets scrollable.

2023-03-09 08:41 UTC, kidroca requested changes

2023-03-09 08:41 UTC, kidroca commented on packages/react/src/components/Table/Table.tsx
> +    <div className="table-container" style={containerStyle}>
Ok, let's add a `className` prop so it can be added to 
```jsx
<div className="table-container" style={containerStyle}>
```

2023-03-09 08:41 UTC, kidroca commented on packages/react/src/components/Table/Table.tsx
> +                ))
Code here expects **perfect data** and can lead to bugs when the `row` has more keys or less keys and not exactly as the number of columns 

This won't work for cases where I pass JSON and want to only display certain columns 
For example I want to display only columns A, B, C, while each row has 100 keys 

Or when some rows might be lacking keys, for example a row is missing key B - the table would render less cells the row and they won't match the columns (everything is shifted to the left)

A table should render a cell for each column, cells shouldn't depend on arbitrary row structure
Something like this:
```suggestion
                columns.map((col) => (
                  col.cellRenderFn
                    ? col.cellRenderFn(col, row)
                    : <td className="table-cell" key={col.key}>{row[col.key]}</td>
                ))
```

Note: we're passing the whole row/col to `col.cellRenderFn(col, row)`, the `cellRenderer` can decide to use `row[col.key]` or if it needs more values from the `row` to render the cell 
While `col` can carry data like cell alignment (so a row can align the same as the header col) or other metadata

2023-03-09 08:41 UTC, kidroca commented on packages/react/src/components/Table/Table.tsx
> +                  ? col.headerRenderFn(index, col.title)
Why do we pass the `index` here: `col.headerRenderFn(index, col.title)` ?
We should just pass the whole `col` object, and let the function use the entire data (if it needs to) 
`col.key` can serve as unique key

2023-03-09 08:41 UTC, kidroca commented on packages/react/src/components/Table/Table.tsx
> +                  : <th key={index} className="table-cell">{col.title}</th>
```suggestion
                  : <th key={col.key} className="table-cell">{col.title}</th>
```

2023-03-09 08:41 UTC, kidroca commented on packages/react/src/components/Table/Table.tsx
> +  cellRenderFn?: (key: string, data: string | number | object) => ReactElement;
Let's omit the `Fn` from the name, it's clear these are functions from the type interface 

```suggestion
  headerRender?: (col: ColumnCell) => ReactElement;
  cellRender?: (col: ColumnCell, data: object) => ReactElement;
```

2023-03-09 08:41 UTC, kidroca commented on packages/react/src/components/Table/Table.tsx
> +export interface ColumnCell {
Let's rename this to `Column` - it's about the entire column and the (column) key used by each row in for that column

2023-03-09 20:00 UTC, kidroca approved these changes
LGTM

2023-03-09 20:23 UTC, merged